//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV2Presets2.Models
{
    using System;
    
    public enum BISSTypeEnum : int
    {
        MODE_1 = 0,
        MODE_E_FIXED = 1,
        MODE_E_TV = 2,
        MODE_E_USER1 = 3,
        MODE_E_USER2 = 4,
        RAS = 5
    }
}
