//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV2Presets2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownlinkChannel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Frequency { get; set; }
        public double SymbolRate { get; set; }
        public PolarisationEnum Polarisation { get; set; }
        public FECEnum FEC { get; set; }
        public RollOffEnum RollOff { get; set; }
        public SDHD SDHD { get; set; }
        public bool EBUChannel { get; set; }
        public ModulationEnum Modulation { get; set; }
        public int SatelliteId { get; set; }
    
        public virtual Satellite Satellite { get; set; }
    }
}
