//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV2Presets2.Models
{
    using System;
    
    public enum encoderLOFreqEnum : int
    {
        Freq_4900_MHz_non_inv = 1,
        Freq_7375_MHz_inv = 2,
        Freq_7600_MHz_inv = 3,
        Freq_7875_MHz_inv = 4,
        Freq_8175_MHz_inv = 5,
        Freq_10000_MHz_non_inv = 6,
        Freq_12800_MHz_non_inv = 7,
        Freq_13050_MHz_non_inv = 8,
        Freq_15450_MHz_non_inv = 9,
        Freq_0_MHz_dir_Lband = 10
    }
}
