//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV2Presets2.Models
{
    using System;
    
    public enum EncoderModulationEnum : int
    {
        QPSK = 1,
        QPSKS2 = 2,
        QPSKS2P = 3,
        Eight_PSK = 4,
        Eight_PSK_S2 = 5,
        Eight_PSK_S2P = 6,
        Sixteen_QAM = 7,
        Sixteen_APSK_S2 = 8,
        Sixteen_APSK_S2P = 9
    }
}
