//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV2Presets2.Models
{
    using System;
    
    public enum EncoderFECEnums : int
    {
        CODE_RATE_14 = 1,
        CODE_RATE_13 = 2,
        CODE_RATE_25 = 3,
        CODE_RATE_12 = 4,
        CODE_RATE_35 = 5,
        CODE_RATE_23 = 6,
        CODE_RATE_34 = 7,
        CODE_RATE_45 = 8,
        CODE_RATE_56 = 9,
        CODE_RATE_78 = 10,
        CODE_RATE_89 = 11,
        CODE_RATE_910 = 12
    }
}
