//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV2Presets2.Models
{
    using System;
    
    public enum FECEnum : int
    {
        NONE = 1,
        FEC12 = 2,
        FEC23 = 3,
        FEC34 = 4,
        FEC56 = 5,
        FEC67 = 6,
        FEC78 = 7,
        FEC89 = 8,
        AUTO = 9,
        FEC14 = 15,
        FEC13 = 16,
        FEC25 = 17,
        FEC35 = 18,
        FEC45 = 19,
        FEC910 = 20,
        FEC1930 = 1930,
        FEC3245 = 3245,
        FEC1730 = 1730
    }
}
