//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV2Presets2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRD
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int MatrixOutput { get; set; }
        public int MatrixInput { get; set; }
        public IRDTypes IRDType { get; set; }
        public string SerialNumber { get; set; }
        public string RegisterNumber { get; set; }
        public string FWVersion { get; set; }
        public string Comments { get; set; }
        public string IPAddress { get; set; }
    }
}
