//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV2Presets2.Models
{
    using System;
    
    public enum IRDTypes : int
    {
        RX8200 = 1,
        TX1260 = 2,
        TX1290 = 3,
        RX8200S2ip = 4
    }
}
