//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV2Presets2.Models
{
    using System;
    
    public enum RollOffEnum : int
    {
        RollOff20 = 0,
        RollOff25 = 2,
        RollOff35 = 1,
        RollOff5 = 3,
        RollOff10 = 4,
        RollOff15 = 5,
        RollOff30 = 6
    }
}
