//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV2Presets2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatellitePosition
    {
        public SatellitePosition()
        {
            this.Satellites = new HashSet<Satellite>();
            this.FixedAntennas = new HashSet<FixedAntenna>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Satellite> Satellites { get; set; }
        public virtual ICollection<FixedAntenna> FixedAntennas { get; set; }
    }
}
