//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV2Presets2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SteerableAntenna
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double Azimuth { get; set; }
        public double Elevation { get; set; }
        public double Polarization { get; set; }
        public string Size { get; set; }
        public string Comment { get; set; }
        public Nullable<int> XHighInput { get; set; }
        public Nullable<int> XLowInput { get; set; }
        public Nullable<int> YHighInput { get; set; }
        public Nullable<int> YLowInput { get; set; }
        public Nullable<double> XHighFreq { get; set; }
        public Nullable<double> XLowFreq { get; set; }
        public Nullable<double> YHighFreq { get; set; }
        public Nullable<double> YLowFreq { get; set; }
    }
}
