//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV2Presets2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UplinkChannel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Satellite { get; set; }
        public double Frequency { get; set; }
        public double SymbolRate { get; set; }
        public PolarisationEnum Polarisation { get; set; }
        public double DataInterfaceRate { get; set; }
        public EncoderFECEnums FEC { get; set; }
        public EncoderRollOffEnum RollOff { get; set; }
        public EncoderModulationEnum Modulation { get; set; }
        public encoderLOFreqEnum LO_Frequency { get; set; }
        public double Power { get; set; }
    }
}
